var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxxxxx        ",
   "                                          xxx      xxxx          xx!!!!xx       ",
   "                                                                 x!!!!!!x       ",
   "                                     o         o                 xx!!!!xx       ",
   "                                   xxxxx                            !!          ",
   "                                    !!!                                         ",
   "                                               o        xxxx                    ",
   "            xxx                xxxxx                                            ",
   "             o      !!!!                    xxxxx                 o o       x   ",
   "             o      xxxx                                                    x   ",
   "    @                                                                       x   ",
   "  xxxxxxx  !!!!  xxxxxxxxxxxxxx       xxxxxxxxxxxxxxx     xxxxxxx!!!!xxxxxxxxx  ",
   "                              x       x             x     x                     ",
   "                              x!!!!!!!x             x!!!!!x                     ",
   "                              x!!!!!!!x             x!!!!!x                     ",
   "                              xxxxxxxxx             xxxxxxx                     ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                            !!!!!!!                                             ",
    "                             !!!!!                                              ",
    "                              !!!                                               ",
    "                               !           o                                    ",
    "                                                xxxx                            ",
    "                                                                                ",
    "             !!!                                                                ",
    "            xxxxx              o    xxxx                                        ",
    "                               o                          o                     ",
    "                      o                                 xxxxx                   ",
    "      @               o                    !!!!!                                ",
    "      xx            xxxxx                   xxxxx                xxxx           ",
    "     xxxx                                                                       ",
    "  !!!xxxx!!!                !!!!!!                                              ",
    "  xxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxx!!!!xxxxxxxxx   ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
